/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file is normally auto-generated by `next dev`/`next build`.
// It's included here so the project has a valid TS entry point even
// before the first run. Do not edit manually.
